# Site settings
title: CDK Front Office Edge Living Styleguide
email: michael.heliker@cdk.com
description: > # this means to ignore newlines until "baseurl:"
  Front Office Edge Living Styleguide
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jekyllrb.com" # the base hostname & protocol for your site
# twitter_username: 
#github_username: 

# Build settings
markdown: rdiscount
rdiscount:
    extensions: [smart]
